package com.ayed.gestionstock.exception;

public enum  errorCodes {
    ART_NOT_FOUND(100),
    ART_NOT_VALID(101),
    CTG_NOT_FOUND(200),
    CTG_NOT_VALID(201),
    CLT_NOT_FOUND(300),
    CLT_NOT_VALID(301),
    CMD_CLT_NOT_FOUND(400),
    CMD_CLT_NOT_VALID(401),
    CMD_CLT_NON_MODIFIABLE(402),
    CMD_CLT_ALREADY_IN_USE(403),
    CMD_FRN_NOT_FOUND(500),
    CMD_FRN_NOT_VALID(501),
    CMD_FRN_NON_MODIFIABLE(502),
    CMD_FRN_ALREADY_IN_USE(503),
    ENT_NOT_FOUND(600),
    ENT_NOT_VALID(601),
    FRN_NOT_FOUND(700),
    FRN_NOT_VALID(701),
    FRN_ALREADY_IN_USE(702),
    LIGNE_CMD_CLT_NOT_FOUND(800),
    LIGNE_CMD_CLT_NOT_VALID(801),
    LIGNE_CMD_FRN_NOT_FOUND(900),
    LIGNE_CMD_FRN_NOT_VALID(901),
    LINGE_VNT_NOT_FOUND(1000),
    LINGE_VNT_NOT_VALID(1001),
    MVT_NOT_FOUND(1100),
    MVT_NOT_VALID(1101),
    MVT_STK_NOT_VALID(1102),
    UTL_NOT_FOUND(1200),
    UTL_NOT_VALID(1201),
    UTL_ALREADY_EXISTS(1202),
    UTL_CHANGE_PASSWORD_OBJECT_NOT_VALID(1203),
    VNT_NOT_FOUND(1300),
    VNT_NOT_VALID(1301),
    VNT_ALREADY_IN_USE(1302),
    UPDATE_PHOTO_EXCEPTION(1400),
    UNKNOWN_CONTEXT(1500);


    private int code;
    errorCodes(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }
}
